version: '3.3'
services:
  odata-front-react:
    build: .
    container_name: "odata-front"
    ports:
      - 3002:3000
    restart: always
    volumes:
      - "./src:/app/src"
      - "./public:/app/public"